name: Discover Repositories from YouTrack Ticket
description: Analyze a YouTrack ticket with AI agent and emit a JSON list of accessible repositories

inputs:
  ticket-id:
    description: 'YouTrack ticket ID'
    required: true
  ticket-title:
    description: 'YouTrack ticket title'
    required: true
  ticket-description:
    description: 'YouTrack ticket description'
    required: true
  github-organization:
    description: 'GitHub organization to check for repositories'
    required: false
    default: 'ideascale'

runs:
  using: composite
  steps:
    - name: Verify OpenCode Installation
      shell: bash
      run: |
        echo "Checking OpenCode installation..."
        which opencode || echo "OpenCode not found in PATH"
        opencode --version || echo "OpenCode command failed"
        echo "Current directory: $(pwd)"
        echo "Config file check:"
        ls -la opencode.json 2>/dev/null || echo "No opencode.json in current directory"
        ls -la ~/.config/opencode/opencode.json 2>/dev/null || echo "No opencode.json in ~/.config/opencode/"

    - name: Build Discovery Prompt
      shell: bash
      run: |
        cat >>"$GITHUB_ENV" <<'EOF'
        PROMPT<<__PROMPT__
        Ticket ID: ${{ inputs.ticket-id }}
        Title: ${{ inputs.ticket-title }}
        Description: ${{ inputs.ticket-description }}

        Task:
        Find repositories that are EXPLICITLY mentioned in the ticket title or description text.

        What counts as explicit mention:
        - Direct repo names: "simple-todo", "user-service", "api-gateway"
        - Repository lists: "repositories: repo1, repo2" or "repos: repo1, repo2"
        - GitHub URLs: "https://github.com/org/repo-name"
        - Specific references: "update the simple-todo repository"

        What does NOT count:
        - General statements like "update the frontend" or "fix the API"
        - Vague references without specific repository names
        - Assumptions about what might need changes

        Instructions:
        - ONLY return repositories that are explicitly named in the ticket text
        - Validate accessibility in the ${{ inputs.github-organization }} org using gh
        - If NO repositories are explicitly mentioned or none of the repos are accessible return empty array
        - Respond with JSON only (no prose, no code fences) in the exact shape:
          { "repositories": ["org/repo", ...] }
        - If none explicitly found, return { "repositories": [] }
        __PROMPT__
        EOF

    - id: ai
      name: Discover Repositories with AI Agent
      shell: bash
      run: |
        set -euo pipefail
        RESPONSE=$(opencode -p "$PROMPT" -q)
        echo "Raw AI response: $RESPONSE" >&2
        REPOS_JSON=$(printf '%s' "$RESPONSE" | jq -c '.repositories // []' 2>/dev/null || echo '[]')
        # Expose as step output for the composite action
        echo "repositories=$REPOS_JSON" >> "$GITHUB_OUTPUT"

outputs:
  repositories:
    description: 'Discovered repositories as a JSON array string (e.g., ["org/repo"])'
    value: ${{ steps.ai.outputs.repositories }}
