name: Set up Claude Environment
description: Set up Node.js, install Claude CLI, and configure YouTrack MCP

inputs:
  node-version:
    description: 'Node.js version to install'
    required: false
    default: '22'
  youtrack-url:
    description: 'YouTrack base URL'
    required: true
  youtrack-token:
    description: 'YouTrack API token'
    required: true
  cloud:
    description: 'Is YouTrack Cloud? (true/false)'
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install Claude CLI
      shell: bash
      run: |
        npm install -g @anthropic-ai/claude-code

    - name: Add npm Global Bin to PATH
      shell: bash
      run: echo "$(npm config get prefix)/bin" >> "$GITHUB_PATH"

    - name: Configure YouTrack MCP Server
      shell: bash
      run: |
        YOUTRACK_URL="${{ inputs.youtrack-url }}" \
        YOUTRACK_API_TOKEN="${{ inputs.youtrack-token }}" \
        YOUTRACK_CLOUD="${{ inputs.cloud }}" \
        claude mcp add youtrack -- \
          docker run -i --rm \
            -e YOUTRACK_URL \
            -e YOUTRACK_API_TOKEN \
            -e YOUTRACK_CLOUD \
            tonyzorin/youtrack-mcp:latest

    - name: Verify MCP Server Registration
      shell: bash
      run: claude mcp list
