name: YouTrack Tag Trigger (dev-bot)

on:
  repository_dispatch:
    types: [ youtrack-tag-dev-bot ]

jobs:
  discover-repos:
    name: Discover Repositories
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    outputs:
      repos: ${{ steps.process.outputs.repositories }}
    steps:
      - name: Checkout Automation Repo
        uses: actions/checkout@v4

      - name: Set up Claude Environment
        uses: ./.github/actions/setup-claude-env
        with:
          node-version: '22'
          youtrack-url: 'https://abrar-sandbox.youtrack.cloud'
          youtrack-token: ${{ secrets.YOUTRACK_API_TOKEN }}

      - name: Discover Repositories from Ticket
        id: process
        uses: ./.github/actions/discover-youtrack-repos
        with:
          ticket-id: ${{ github.event.client_payload.issueId }}
          ticket-title: ${{ github.event.client_payload.title }}
          ticket-description: ${{ github.event.client_payload.description }}
          github-organization: 'abrar-sandbox'
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

  aggregate-plan:
    name: Generate Plans and Create Issues
    needs: [ discover-repos ]
    if: ${{ needs.discover-repos.outputs.repos != '' && needs.discover-repos.outputs.repos != '[]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout Automation Repo
        uses: actions/checkout@v4

      - name: Set up Claude Environment
        uses: ./.github/actions/setup-claude-env
        with:
          node-version: '22'
          youtrack-url: 'https://abrar-sandbox.youtrack.cloud'
          youtrack-token: ${{ secrets.YOUTRACK_API_TOKEN }}

      - name: Clone Target Repositories
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          REPOS_JSON: ${{ needs.discover-repos.outputs.repos }}
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p repos
          echo "$REPOS_JSON" | jq -r '.[]' | while read -r R; do
            SAFE=$(echo "$R" | tr '/' '__')
            echo "Cloning $R into repos/$SAFE"
            git clone --depth 1 "https://x-access-token:${GH_PAT}@github.com/${R}.git" "repos/$SAFE"
          done

      - name: Build Cross-Repo Analysis Prompt (Claude will post plans as issues on Github and comment on Youtrack)
        env:
          TICKET_ID: ${{ github.event.client_payload.issueId }}
          TITLE: ${{ github.event.client_payload.title }}
          DESC: ${{ github.event.client_payload.description }}
          REPOS_JSON: ${{ needs.discover-repos.outputs.repos }}
          YOUTRACK_URL: 'https://abrar-sandbox.youtrack.cloud'
        shell: bash
        run: |
          cat >>"$GITHUB_ENV" <<'EOF'
          PROMPT<<__PROMPT__
          YouTrack Ticket:
          - ID: ${TICKET_ID}
          - Title: ${TITLE}
          - Description:
          ${DESC}

          Context:
          - All repositories are checked out under the current working directory (repos/). Each repo is in a subfolder named "org__repo" (slash replaced by double underscore).
          - You may read actual files and directories as needed to form an implementation plan across repos. Avoid exhaustive scans; prioritize manifests, entrypoints, services, and files relevant to the ticket.
          - The GitHub CLI (gh) is available and authenticated via token environment. The YouTrack MCP server is registered as "youtrack" and can be used to post comments.

          Task:
          - Analyze the checked-out repositories and the ticket requirements.
          - For each repo in ${REPOS_JSON} that exists under repos/, craft a repo-specific implementation plan and then create a GitHub issue via gh.
          - Issue title MUST be exactly: "${TICKET_ID} ${TITLE}".
          - Issue body MUST include a hyperlink to the YouTrack ticket: [${TICKET_ID}](${YOUTRACK_URL}/issue/${TICKET_ID}), followed by the repo-specific plan (Markdown allowed: checklist and acceptance criteria encouraged). Ensure content is tailored to each repo and references actual files/paths.
          - Note cross-repo dependencies where relevant.
          - After creating issues, post a single comment to YouTrack ticket ${TICKET_ID} listing the created issue links using the YouTrack MCP tool named "youtrack".
          - Finally, print a concise summary of actions taken (e.g., JSON mapping repos to created issue URLs) for logging.
          __PROMPT__
          EOF

      - name: Invoke Claude with Prompt
        working-directory: repos
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_PAT }}
        shell: bash
        run: |
          set -euo pipefail
          RESPONSE=$(printf '%s' "$PROMPT" | claude --dangerously-skip-permissions)
          echo "$RESPONSE"

      # - name: SSH into runner to Debug
      #   uses: owenthereal/action-upterm@v1

  no-repos:
    name: "Notify YouTrack: No Repositories Found"
    needs: [ discover-repos ]
    if: ${{ needs.discover-repos.outputs.repos == '' || needs.discover-repos.outputs.repos == '[]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Comment on YouTrack to Request Repository Mentions
        env:
          YOUTRACK_API_TOKEN: ${{ secrets.YOUTRACK_API_TOKEN }}
          TICKET_ID: ${{ github.event.client_payload.issueId }}
        shell: bash
        run: |
          set -euo pipefail
          TEXT=$'No accessible repositories were identified from this ticket.\n\nPlease specify repositories explicitly in the description using the format:\n\nrepositories: repo1, repo2, repo3\n\nAfter updating the ticket, re-trigger the workflow.'
          COMMENT_PAYLOAD=$(jq -n --arg text "$TEXT" '{text: $text}')
          curl -sS -X POST \
            -H "Authorization: Bearer ${YOUTRACK_API_TOKEN}" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            "https://abrar-sandbox.youtrack.cloud/api/issues/${TICKET_ID}/comments?fields=id,text,author(login)" \
            -d "$COMMENT_PAYLOAD"
