name: On Youtrack Tag dev-bot

on:
  repository_dispatch:
    types: [ youtrack-tag-dev-bot ]

jobs:
  plan-ticket-solution:
    uses: ./.github/workflows/analyse-ticket.yml
    with:
      ticket_id: ${{ github.event.client_payload.issueId }}
      title: ${{ github.event.client_payload.title }}
      description: ${{ github.event.client_payload.description }}
      youtrack_url: 'https://abrar-sandbox.youtrack.cloud'
      github_organization: 'abrar-sandbox'
    secrets:
      YOUTRACK_API_TOKEN: ${{ secrets.YOUTRACK_API_TOKEN }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      GH_PAT: ${{ secrets.GH_PAT }}

